Update scrollToRow value, when user scrolled list
ubergrape/grape-web-client pull request #1267
Opened 2021-04-19 14:04 UTC by AleshaOleg

I tested with passing `isKeyboardNavigationEnabled` prop for list in "People" tab.
What I did, is updating the selected item (which is supposed to be selected with keyboard navigation) when the user scrolling.

Behavior not perfect, but still much much better than it was.
As the user most likely stopped scrolling somewhere in the middle of the item, so the first item from visible items not fully visible. That's why a small jump occurs when the user stops scrolling.

2021-04-19 14:05 UTC, AleshaOleg commented on src/components/list/InfiniteAutoRowHeightList.js
> +                      if (
This `if` condition basically the only change I did in the list logic

2021-04-20 09:02 UTC, sk7 requested changes
I'm not sure how to fix it but it still jumps, see other comment

2021-04-20 09:02 UTC, sk7 commented on src/components/list/InfiniteAutoRowHeightList.js
> +                          scrollToRow: index,
now it doesn't jump to the first user but still jumps.

as soon as is top scrolling, I think it scrolls the the last visible user currently, which is almost never exactly at the scroll position where the code wants it to be, so this looks like a confusing jump.

2021-04-20 11:08 UTC, AleshaOleg commented
@sk7 updated PR, now updating `scrollToIndex` property for List manually and only when a user using keyboard navigation. Works correctly now.

2021-04-20 13:00 UTC, merged

2021-04-20 13:00 UTC, sk7 commented
Note: keyboard navigation is quite slow, but still merging this