Added links for Privacy Policy and TOS
ubergrape/grape-web-client pull request #1308
Opened 2021-05-26 22:44 UTC by AleshaOleg

2021-06-01 14:48 UTC, sk7 reviewed
the urls for both items are dynamic and come from the server in some RPC call. the urls are different for Untis for example.

2021-06-01 14:49 UTC, sk7 requested changes

2021-06-01 14:49 UTC, sk7 commented on src/components/org-info/menuItems.js
> +    href="https://www.grape.io/privacy"
here

2021-06-01 14:49 UTC, sk7 commented on src/components/org-info/menuItems.js
> +    href="https://www.grape.io/terms-of-service"
and here

2021-06-04 09:03 UTC, AleshaOleg commented on src/components/org-info/menuItems.js
> +    href="https://www.grape.io/privacy"
thanks, fixed it.

2021-06-04 09:03 UTC, AleshaOleg commented on src/components/org-info/menuItems.js
> +    href="https://www.grape.io/terms-of-service"
thanks

2021-06-09 15:59 UTC, merged